### PR TITLE
Show hosts memory in relation to each other

### PR DESCRIPTION
**Pull request by borzel**
New Option:

grafik

Option disabled (default): All hosts have the same length, but different amount of memory

grafik

Option enabled: All hosts are just as long as they have memory :-)

grafik

https://github.com/xcp-ng/xenadmin/issues/19 Pool Memory Tab: show memory in relation to each other

### CODE REVIEW

**Comment by olivierlambert** [comment]
You really should make a PR against the mainline, or you'll need to maintain the diff in the fork, which could be painful.

**Comment by borzel** [comment]
@olivierlambert first steps in the right direction: https://github.com/xenserver/xenadmin/pull/2053

**Comment by borzel** [comment]
Fix for upstream: https://github.com/xenserver/xenadmin/pull/2054

**Comment by borzel** [comment]
**TODOs**
* [ ] create better settings pages
* [ ] update Memory Tab after changing the settings

**Comment by borzel** [comment]
Note to myself: do it better in master :-)

**Pull request closed without merging**
