### PR TITLE
Fast fix for new xcp-ng 8.2

### PR DESCRIPTION
**Pull request by splastunov**
It is just workaround to start XCP-ng Center without error.

### CODE REVIEW

**Comment by stormi** [comment]
FYI @cocoon also has a temporary fork of this repo and built a new XCP-ng Center.

I'll let him or another contributor review your PR.

**Comment by splastunov** [comment]
Hello!

First of all I made git diff with @cocoon fork.
There are a lot of changes and I'm not sure that I need all of them.
To make xcp-ng Center work with new xcp-ng 8.2 we need just to add a few lines that I have added.

**Comment by olivierlambert** [comment]
If you aren't sure yourself, it doesn't mean it's not needed :wink:  Right here and right now, there's 2 people who seem to know more, and got the repository permissions to decide what to do: @cocoon and @borzel

**Comment by splastunov** [comment]
> If you aren't sure yourself, it doesn't mean it's not needed 😉 Right here and right now, there's 2 people who seem to know more, and got the repository permissions to decide what to do: @cocoon and @borzel

Of course, you are right.

This is just my 2 cents for community : )

**Review by schulz-alexander — APPROVED** [review]

**Comment by olivierlambert** [comment]
Aaaand here it comes!

**Pull request merged**
